print("Welcome to Learning of Python")
print(20*9)
print("This is my first Python beginners")
print("Python for Beginners")
print("This is a very powerful programming language")
print("Python is used in developing of web applications")